package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Department;
import org.mybatis.cdi.Mapper;

import javax.enterprise.context.ApplicationScoped;

@Mapper
public interface DepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DEPARTMENT
     *
     * @mbg.generated Tue Apr 18 23:39:33 EEST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DEPARTMENT
     *
     * @mbg.generated Tue Apr 18 23:39:33 EEST 2023
     */
    int insert(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DEPARTMENT
     *
     * @mbg.generated Tue Apr 18 23:39:33 EEST 2023
     */
    Department selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DEPARTMENT
     *
     * @mbg.generated Tue Apr 18 23:39:33 EEST 2023
     */
    List<Department> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DEPARTMENT
     *
     * @mbg.generated Tue Apr 18 23:39:33 EEST 2023
     */
    int updateByPrimaryKey(Department record);
}