package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Project;
import org.mybatis.cdi.Mapper;

@Mapper
public interface ProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PROJECT
     *
     * @mbg.generated Tue Apr 18 23:39:33 EEST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PROJECT
     *
     * @mbg.generated Tue Apr 18 23:39:33 EEST 2023
     */
    int insert(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PROJECT
     *
     * @mbg.generated Tue Apr 18 23:39:33 EEST 2023
     */
    Project selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PROJECT
     *
     * @mbg.generated Tue Apr 18 23:39:33 EEST 2023
     */
    List<Project> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PROJECT
     *
     * @mbg.generated Tue Apr 18 23:39:33 EEST 2023
     */
    int updateByPrimaryKey(Project record);
}