package lt.vu.mybatis.model;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EMPLOYEE.ID
     *
     * @mbg.generated Tue Apr 18 23:39:33 EEST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EMPLOYEE.NAME
     *
     * @mbg.generated Tue Apr 18 23:39:33 EEST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EMPLOYEE.DEPARTMENT_ID
     *
     * @mbg.generated Tue Apr 18 23:39:33 EEST 2023
     */
    private Integer departmentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EMPLOYEE.ID
     *
     * @return the value of PUBLIC.EMPLOYEE.ID
     *
     * @mbg.generated Tue Apr 18 23:39:33 EEST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EMPLOYEE.ID
     *
     * @param id the value for PUBLIC.EMPLOYEE.ID
     *
     * @mbg.generated Tue Apr 18 23:39:33 EEST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EMPLOYEE.NAME
     *
     * @return the value of PUBLIC.EMPLOYEE.NAME
     *
     * @mbg.generated Tue Apr 18 23:39:33 EEST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EMPLOYEE.NAME
     *
     * @param name the value for PUBLIC.EMPLOYEE.NAME
     *
     * @mbg.generated Tue Apr 18 23:39:33 EEST 2023
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EMPLOYEE.DEPARTMENT_ID
     *
     * @return the value of PUBLIC.EMPLOYEE.DEPARTMENT_ID
     *
     * @mbg.generated Tue Apr 18 23:39:33 EEST 2023
     */
    public Integer getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EMPLOYEE.DEPARTMENT_ID
     *
     * @param departmentId the value for PUBLIC.EMPLOYEE.DEPARTMENT_ID
     *
     * @mbg.generated Tue Apr 18 23:39:33 EEST 2023
     */
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }
}